---
# tasks file for redis
- name: install lsb-release curl gpg
  shell:
    cmd: "sudo apt install -y lsb-release curl gpg"

- name: install gnupg
  shell:
    cmd: "apt-get install -y gnupg"

- name: download redis
  shell:  
    cmd: "curl -fsSL https://packages.redis.io/gpg -o- | gpg --dearmor > /usr/share/keyrings/redis-archive-keyring.gpg"
    
- name: redis list
  shell:
    cmd: 'echo "deb [signed-by=/usr/share/keyrings/redis-archive-keyring.gpg] https://packages.redis.io/deb $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/redis.list'
    
- name: apt update
  shell:
    cmd: "apt-get update"

- name: install redis
  shell:
    cmd: "apt-get install -y redis"
    
- name: enable redis
  shell:
    cmd: "systemctl enable redis-server.service"
