---
# tasks file for elastic_kibana
- name: Instalamos o Elastic P1
  shell:
    cmd: "wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | gpg --dearmor -o /usr/share/keyrings/elasticsearch-keyring.gpg"

- name: Instalamos o Elastic P2
  shell:
    cmd: "apt-get install apt-transport-https"

- name: Instalamos o Elastic P3
  shell:
    cmd: "echo "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main" | tee /etc/apt/sources.list.d/elastic-8.x.list"

- name: Instalamos o Elastic P4
  shell:
    cmd: "apt-get update && apt-get install elasticsearch"

read -p "GUARDA A INFORMAÇÃO DE CIMA!! PASSWORD AND TOKEN !! NEXT Press any key to continue ..."

- name: enable do Elastic P1
  shell:
    cmd: "sudo systemctl daemon-reload"

- name: enable do Elastic P2
  shell:
    cmd: "sudo systemctl enable elasticsearch.service"

- name: enable do Elastic P3
  shell:
    cmd: "sudo systemctl start elasticsearch.service"

- name: apt-get update
  shell:
    cmd: "apt-get update"

- name: Install Kibana
  shell:
    cmd: "apt-get install kibana"

######################

## falta terminar  http://192.168.1.214:30001/books/solucao-k8s-bsimple/page/instalacao-de-elastic-e-kibana-em-maquina-isolada-bsimple

8-Configurar o config do Kibana
1-onde tem o IP tinha localhost comentado (descomentar e colocar o IP)

2- publicbaseurl (adicionamos uma linha nova e colocamos o endereço que vamos chamar)

###########################


- name: Start Kibana
  shell:
    cmd: "systemctl start kibana.service"
    
- name: TOken Kibana
  shell:
    cmd: "/usr/share/elasticsearch/bin/elasticsearch-create-enrollment-token -s kibana"
    
    
# user: elastic
# pass: a que foi gerada de super user na instalação do elastic.

