---
# tasks file for rabbitmq
- name: apt-transport-https
  shell:
    cmd: "apt install curl gnupg apt-transport-https -y"
    
- name: Team RabbitMQ's main signing key
  shell:
    cmd: "curl -1sLf "https://keys.openpgp.org/vks/v1/by-fingerprint/0A9AF2115F4687BD29803A206B73A36E6026DFCA" | gpg --dearmor | tee /usr/share/keyrings/com.rabbitmq.team.gpg > /dev/null"



- name:  Cloudsmith: modern Erlang repository
  shell:
    cmd: "curl -1sLf https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-erlang/gpg.E495BB49CC4BBE5B.key | gpg --dearmor | tee /usr/share/keyrings/io.cloudsmith.rabbitmq.E495BB49CC4BBE5B.gpg > /dev/null"

- name:  Cloudsmith: RabbitMQ repository
  shell:
    cmd: "curl -1sLf https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-server/gpg.9F4587F226208342.key | gpg --dearmor | tee /usr/share/keyrings/io.cloudsmith.rabbitmq.9F4587F226208342.gpg > /dev/null"

- name:  Add apt repositories maintained by Team RabbitMQ
  shell:
    cmd: "tee /etc/apt/sources.list.d/rabbitmq.list <<EOF"

- name:  Provides modern Erlang/OTP releases 1
  shell:
    cmd: "deb [signed-by=/usr/share/keyrings/io.cloudsmith.rabbitmq.E495BB49CC4BBE5B.gpg] https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-erlang/deb/ubuntu bionic main"

- name: Provides modern Erlang/OTP releases 2
  shell:
    cmd: "deb-src [signed-by=/usr/share/keyrings/io.cloudsmith.rabbitmq.E495BB49CC4BBE5B.gpg] https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-erlang/deb/ubuntu bionic main"

- name: Provides RabbitMQ
  shell:
    cmd: "deb [signed-by=/usr/share/keyrings/io.cloudsmith.rabbitmq.9F4587F226208342.gpg] https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-server/deb/ubuntu bionic main"

- name: Provides RabbitMQ
  shell:
    cmd: "deb-src [signed-by=/usr/share/keyrings/io.cloudsmith.rabbitmq.9F4587F226208342.gpg] https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-server/deb/ubuntu bionic main"

- name: Provides RabbitMQ
  shell:
    cmd: "EOF"

- name: Update package indices
  shell:
    cmd: "apt update -y"

- name: Install Erlang packages
  shell:
    cmd: "apt install -y erlang-base \
                        erlang-asn1 erlang-crypto erlang-eldap erlang-ftp erlang-inets \
                        erlang-mnesia erlang-os-mon erlang-parsetools erlang-public-key \
                        erlang-runtime-tools erlang-snmp erlang-ssl \
                        erlang-syntax-tools erlang-tftp erlang-tools erlang-xmerl"

- name: Install rabbitmq-server and its dependencies
  shell:
    cmd: "apt install rabbitmq-server -y --fix-missing"
    
    
    ######## esta parte nao ta bem tratar ######### http://192.168.1.214:30001/books/solucao-k8s-bsimple/page/instalacao-de-rabbitmq-em-maquina-isolada-bsimple
    
- name: Alterar este ficheiro e descomentar o nodeport e mudar o hostname (Meter o nome da maquina "rabitmq-deb")
  shell:
    cmd: "vim /etc/rabbitmq/rabbitmq-env.conf"
    
    - NODENAME=<hostname>
    - NODE_PORT=5672
    
    ######## esta parte nao ta bem tratar ######### http://192.168.1.214:30001/books/solucao-k8s-bsimple/page/instalacao-de-rabbitmq-em-maquina-isolada-bsimple
    
- name: Activar o web API - enable WEB API
  shell:
    cmd: "rabbitmq-plugins enable rabbitmq_management"
    
- name: Criar utilizador de admin 1
  shell:
    cmd: "rabbitmqctl add_user admin mudapassw0rd"
    
- name: Criar utilizador de admin 2
  shell:
    cmd: "rabbitmqctl set_user_tags admin administrator"