---
# vars file for nodes
iptables: "net.bridge.bridge-nf-call-iptables  = 1"
forward:  "net.ipv4.ip_forward                 = 1"
ip6tables:  "net.bridge.bridge-nf-call-ip6tables = 1"
over: "overlay"
net: "br_netfilter"
iface: "iface enp0s8 inet static"
address:  "   address: {{inventory_hostname}}"
gateway:  "   gateway: 192.168.1.260" # ajustar conforme range do IP
netmask:  "   netmask: 255.255.260.0"
xenial: "deb https://apt.kubernetes.io/ kubernetes-xenial main"
