---
# tasks file for master
- name: Baixando o Calico.yaml
  shell:             # comando que daria no terminal á no host
    cmd: "wget https://docs.projectcalico.org/manifests/calico.yaml"

- name: Criando o Cluster com kubeadm
  shell:             
    cmd: "sudo kubeadm init"

- name: Configurar conta no Control Plane Node para ter acesso administrativo ao APIServer (step1)
  shell:             
   cmd: "mkdir -p $HOME/.kube"

- name: Step 2
  shell:             
    cmd: "sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config"

- name: Step 3
  shell:             
    cmd: "sudo chown $(id -u):$(id -g) $HOME/.kube/config"

- name: Criando Pod Network com o deployment yaml
  shell:             
    cmd: "kubectl apply -f calico.yaml"

- name: Instalar o CLI do calico
  shell:             
    cmd: "curl -L https://github.com/projectcalico/calico/releases/download/v3.24.0/calicoctl-linux-amd64 -o calicoctl"

- name: Permissão arquivo calicoctl
  shell:             
    cmd: "chmod +x ./calicoctl"
  
- name: Obter o ficheiro -yaml com a configuração da IPPoolcalicoctl get ippool --allow-version-mismatch -o yaml
  shell:             
    cmd: "sudo calicoctl get ippool --allow-version-mismatch -o yaml"

- name: Aplicar as alterações
  shell:             
    cmd: "sudo calicoctl apply -f pools.yaml --allow-version-mismatch"